#!/usr/bin/env python
# Copyright 2016 Michael J Maurer
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import sys
from dfvfs_utils.dfvfs_util import DfvfsUtil

__version__ = '0.1.0'

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Outputs the contents of a file based on its pathspec.')
    parser.add_argument('pathspec', help=u'Encoded pathspec')
    parser.add_argument(u'-v', u'--version',
                        help=u'Prints version',
                        action=u'store_true')
    reload(sys)
    sys.setdefaultencoding('utf-8')
    args = parser.parse_args()
    if args.version:
        print args.version

    dfvfs_util = DfvfsUtil()
    dfvfs_util.export_file(dfvfs_util.decode_pathspec(args.pathspec))
