#!/usr/bin/env python
# Copyright 2016 Michael J Maurer
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import os
import sys
from dfvfs_utils.dfvfs_util import DfvfsUtil

__version__ = '0.1.0'

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description='Gets the pathspec and other information from an evidence item or pathspec.')
    parser.add_argument('pathspec', help=u'Encoded pathspec or path to evidence')
    parser.add_argument(u'-v', u'--version',
                        help=u'Prints version',
                        action=u'store_true')
    reload(sys)
    sys.setdefaultencoding('utf-8')
    args = parser.parse_args()
    if args.version:
        print args.version

    dfvfs_util = DfvfsUtil()
    pathspec = []

    try:
        pathspec = dfvfs_util.decode_pathspec(args.pathspec)
    except:
        if not os.path.isfile(args.pathspec) and not os.path.isdir(args.pathspec):
            sys.stderr.write('Value "' + args.pathspec + '" is not a valid pathspec or file')
            sys.exit(1)
        dfvfs_util = DfvfsUtil(args.pathspec)
        pathspec = dfvfs_util.base_path_specs

    dfvfs_util.print_pathspec(pathspec)